### ISSUE TITLE
Get started with OBS

### ISSUE THREAD

**Issue by dob** [livepeer/docs#2]
As suggested in: https://github.com/livepeer/go-livepeer/issues/308#issuecomment-369113251

We should have a get started with OBS doc that explains the detailed settings to use in OBS to use Livepeer.

**Comment by chrishobcroft** [comment]
How is this: https://github.com/livepeer/docs/blob/master/docs/source/configuringOBSandLivepeer

**Comment by j0sh** [comment]
Looks great! Just a few small comments:

Maybe change the file extension to .md since it looks more-or-less Markdown, so Github should be able to render a pretty version.

> running `Linux` or Apple Mac

Do we have a preferred distro or minimum supported MacOS release? Might be worth mentioning that releases are built for x86-64, so folks aren't surprised when Livepeer can't run on their Raspbian.

> connected to internet with at least 220kbps upload bandwidth, e.g. 2G Mobile Internet

I don't think 2G would make for very usable broadcasts :) And I'm afraid that 220kbps is too low, but the minimum required is a function of the broadcast bitrate. Also, should we emphasize wired Internet for better reliability? Maybe we could say something like

> connected to the Internet using a wired connection. Upload requirements are based on the bitrate you plan to broadcast at, but in general give yourself 50% overhead. So for a 2mbps stream, make sure you have 3mbps available.

Of course, that's a lot more verbose that those bullet points we have going there.

> with power supply 

Because encoding will chew through battery? In general I think it's also useful to give the reason behind the recommendations. Maybe say "Connected to a power source, because encoding is computationally heavy."

> - an account on twitter, facebook or google+

In the spirit of explaining the reason, maybe say this is to get test eth. Some people get annoyed when social verification is required, and we don't want to give the impression that Livepeer requires it. Maybe simply replace that bullet with "test eth to pay for broadcasting" ? Then in Section 1.3.3 , mention the social requirement in order to get test eth?

For the OBS sections, screenshots would be really helpful for new users.

**Comment by dob** [comment]
Yah looking good. Agree with a lot of Josh's comments. 

Maybe add the .md extension, preview it in http://markdownlivepreview.com/, and then when it's ready to go we can add it to the index.rst table of content or link it from the other docs.

For what it's worth, it's also better to submit this request as a Pull Request rather than commit directly to master, so that we can give comments and make updates before it gets deployed live on readthedocs. (pushes to master get immediately deployed). The way to do this is to press "Fork", and then you'll have your own copy you can edit. Then from that copy, it will ask if you want to submit a PR back into this repo, and you can do it that way.

**Comment by chrishobcroft** [comment]
I'm keen to emphasize the minimum entry level for running a stream from OBS, which is 220kbps = 200kbps video + 20kbps audio.

It would be shitty, or could be low frame-rate, but it would work, and could help people in places with weaker internet connections to start streaming. Not everyone has fiber broadband :)

But as you say, some headroom is nice, so I've changed it to 330kbps.

**Comment by chrishobcroft** [comment]
And with the wired / wireless, I think it's important, but also I don't think it's so important to mention, to seek to keep it simple.

For example, I'm doing a lot of 4G streaming and it works pretty well.

**Comment by chrishobcroft** [comment]
Updated and migrated to .md

https://github.com/livepeer/docs/blob/master/docs/source/configuringOBSandLivepeer.md

Is this ready to be incorporated into the index.rst?

**Comment by dob** [comment]
Excellent. Mind if I make a few formatting changes and link it to the
index? For future reference the formatting changes I'm suggesting mostly
have to do with:

* Reserve the backticks for code content or executable commands meant to be
typed in a terminal.

**Comment by chrishobcroft** [comment]
```
Sure.
```

Maybe I've been getting a little `too` creative with the markdown?

**Comment by chrishobcroft** [comment]
@dob can we close this now?
